# Change these first
owner: teaclientmc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main Website
    url: https://teaclient.net
    slug: main
    assignees: 
      - Eveeifyeve
      - Coffee-Nerd
  - name: Docs Site
    url: https://docs.teaclient.net
    slug: docs
    assignees: 
      - Eveeifyeve
      - Coffee-Nerd

status-website:
  cname: status.teaclient.net
  # baseurl: /
  logoUrl: https://avatars.githubusercontent.com/u/136329178?s=200&v=4
  name: TeaClient Status
  introTitle: TeaClient New Status Page
  introMessage: Wellcome to our status page 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Any issues? Contact us.
      href: https://discord.com/invite/ejFTe4Hfnc
commitMessages:
  readmeContent: "chore: update summary in readme"
  summaryJson: "chore: update status summary"
  statusChange: "chore: $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms)"
  graphsUpdate: "chore: update graphs"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
